### PR TITLE
Ts refactor tools

### PR DESCRIPTION
**Pull request by TomSmithCGAT**
Hi Ian,

I've made a number of significant changes, hence the branch.

- The directory structure has been changed so the two scripts are in the tools directory. 
- A setup.py and umi_tools.py have been added to allow installation of UMI-tools package and execution on the command line (e.g umi_tools extract ...). The setup.py is a simplified version of CGAT scripts setup.py, umi_tools.py simplified cgat.py
- Documentation updated to reflect new installation and execution

Please feel free to fetch my branch and make changes to the names of the tools etc as you wish. 

Apologies for all the documentation commits, I forgot that it's possible to update an rst directly on github and preview the rendered README.

### CODE REVIEW

**Comment by IanSudbery** [comment]
Hi Tom, thanks for this, I'll have a play with it. Did you think about dependency installation?

**Comment by TomSmithCGAT** [comment]
Hi Ian,

Setup.py checks for cython and pysam and python >=2.7. I haven't checked whether UMI-tools is python 3 compatible yet? If not, I guess we should make it so.

Now you mention it, I realise that I've also removed the section which parses requires.txt to identify the installation requirements. I'll add that back in along with a requires.txt so numpy and pandas are covered too.

Cheers,

Tom

Tom Smith, PhD
CGAT Training Fellow | http://www.cgat.org<https://owa.nexus.ox.ac.uk/owa/redir.aspx?C=tg_bDY9IpU-WsZT9DRtecLrzBQBo5dAIR2VtNMFUhhmiSbB621cWM1yWzPrEKkt2W6Kx2kZl0Lg.&URL=http%3a%2f%2fwww.cgat.org>
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
https://cgatoxford.wordpress.com/author/tss505/
________________________________

**Comment by IanSudbery** [comment]
We depend on CGAT, and CGAT is not python 3 compatible. Also, I guess automatic installation of CGAT might be a pain in general, as we seem to be moving to recommending people run CGAT in a isolated environment.

**Comment by TomSmithCGAT** [comment]
Hmmm, very good point.

Perhaps it's time to sever the CGAT dependency? We're only using the parser and logging from Experiment.py, IOTools.openFile() and Fastq.iterate. What do you say to a single UMI-tools module file with the these functions?


________________________________

**Comment by IanSudbery** [comment]
Hmmm…. Seems, copying directly from the CGAT code seems a bit cheeky, but
it would make installation a million times easier.

**Comment by TomSmithCGAT** [comment]
The IOTools and Fastq functions are so basic that it would barely constitute copying. It's really just the CGAT derivative of optparse.OptionParser which we'd be copying. Seems like an awfully small chunk of code to justify the CGAT dependency.

Ah ha, the CGAT derivate already borrows code and includes the relevant copyright notice:

# The code for BetterFormatter has been taken from
# http://code.google.com/p/yjl/source/browse/Python/snippet/BetterFormatter.py

Seems to me we should go ahead and do the same and make clear where the OptionParser code for BetterFormatter and  AppendCommanOption comes from?

Tom

________________________________

**Comment by IanSudbery** [comment]
Well I’m in favour of breaking the CGAT dependency if possible: it just
makes installation SO much easier, it just makes me feel like a bad citizen
for not pushing CGAT adoption J.



Ian

**Comment by TomSmithCGAT** [comment]
Yeah I know what you mean. I'll check with Andreas...

________________________________

**Comment by AndreasHeger** [comment]
Makes perfect sense to remove the dependency.

Best wishes,
Andreas

**Comment by TomSmithCGAT** [comment]
Cheers Andreas.

Ian, I'll do this on the branch so I can test everything post the complete refactoring before we merge with master.

**Pull request closed without merging**
