### PR TITLE
Suggest installation via bioconda instead of custom channel.

### PR DESCRIPTION
**Pull request by johanneskoester**
This also increases interoperability with other tools.

### CODE REVIEW

**Comment by TomSmithCGAT** [comment]
I'm happy with this. @IanSudbery?

**Comment by IanSudbery** [comment]
Is the version on bioconda up-to-date? If so then we should definately be recommending bioconda.

**Comment by johanneskoester** [comment]
Yes, it is the same as in your channel, and you are very welcome to maintain the recipe in bioconda (either via pull requests from a fork, or via joining your team).

**Comment by johanneskoester** [comment]
xref: https://anaconda.org/search?q=umi_tools

**Comment by johanneskoester** [comment]
We also have automatic testing and a convenient build infrastructure for our recipes, so maintenance will even be easier for you.

**Comment by IanSudbery** [comment]
Thanks @johanneskoester, I definately think that it is better to not do things on custom channels.

**Pull request merged**
