### PR TITLE
{ts} debug missing tag

### PR DESCRIPTION
**Pull request by TomSmithCGAT**
This enables reads missing a UMI or CB tag to be skipped rather than throwing an error (See #276).

As part of this, I've also moved the check for UMI/CB tags to before the check for bundle yielding as per all the other checks which cause reads to be skipped.

### CODE REVIEW

**Comment by TomSmithCGAT** [comment]
@IanSudbery - nudge nudge

**Comment by ZHUwj0** [comment]
Hi @TomSmithCGAT,

Today, I just downloaded UMI-Tools: Version 1.0.0, and try to use it to do umi_tools dedup on BAM files from cellranger (10X genomics data).   However, I still have the error, "KeyError: "tag 'CB' not present". 
I noticed that you actually fixed this issue before.  is it possible for you to check whether this bug had been fixed or not, again?   
many thanks. 

Best regards, 
Wenjuan

**Comment by ZHUwj0** [comment]
For example,  NH:i:1  HI:i:1  AS:i:69 nM:i:9  RE:A:I  xf:i:0  li:i:0  CR:Z:CCGTAGACACTGTGTA   CY:Z:FFFFFFFFFFFFFFFF   UR:Z:TCAGGAACCG UY:Z:FFFFFFFFFF UB:Z:TCAGGAACCG RG:Z:1823_BA24:0:1:HCC5FDMXX:1

**Comment by TomSmithCGAT** [comment]
Hi Wenjun,

by default, UMI-tools expects the cell barcodes to be provided in the 'CB' tag. If you have another tag denoting the cell barcode, you can add the option `--cell-tag=CELL_TAG`, where `CELL_TAG` appears to be `CR` in your example above

**Comment by ZHUwj0** [comment]
Hi @TomSmithCGAT,
yes, I knew this. Here is my command:
umi_tools dedup --per-cell --output-stats=sample --stdin=test.bam --stdout=test.dedup.bam --extract-umi-method=tag --umi-tag=UB --cell-tag=CB. 

However,  In BAM files from cellranger standard pipeline,  the majority of lines have the CB tag.  But, some lines do not have CB tag, like this one. 
NH:i:1 HI:i:1 AS:i:69 nM:i:9 RE:A:I xf:i:0 li:i:0 CR:Z:CCGTAGACACTGTGTA CY:Z:FFFFFFFFFFFFFFFF UR:Z:TCAGGAACCG UY:Z:FFFFFFFFFF UB:Z:TCAGGAACCG RG:Z:1823_BA24:0:1:HCC5FDMXX:1

Possibly that is why umi_tools had this error, "KeyError: "tag 'CB' not present". 

Best regards, 
Wenjuan

**Comment by TomSmithCGAT** [comment]
Ah I see. Sorry, I misunderstood the problem. I'll take another look at this now

**Comment by TomSmithCGAT** [comment]
I can't see any obvious reason why this would happen. This should be caught here: https://github.com/CGATOxford/UMI-tools/blob/6945f6ae5a9a7c56fdac22f2caddec4246442bc2/umi_tools/sam_methods.py#L411-L427

 Would you mind posting the full error message here so I can see where the KeyError originates and confirming your version number (`umi_tools --version`)

**Comment by ZHUwj0** [comment]
Please check this file including the error and real example of BAM file. 
[test.zip](https://github.com/CGATOxford/UMI-tools/files/3931643/test.zip)

You may want to use this small BAM file to test software. 

many thanks.

**Comment by TomSmithCGAT** [comment]
Ah, right, got it! The problem is that the KeyError originates from the parsing of the BAM to generate the null distribution for the stats (code below) rather than the parsing for deduplication (code above). I'll add a patch for this now.

https://github.com/CGATOxford/UMI-tools/blob/5e99b633932d7de7591cd9881db8745295ccb500/umi_tools/umi_methods.py#L164-L172

**Comment by TomSmithCGAT** [comment]
Hi Wenjuan,

Could you test the version of UMI-tools on the `{TS}-DebugCellTag` branch. This works with the test BAM so should be fine but just want to be sure before pushing changes to the master.

Thanks,

Tom

**Comment by ZHUwj0** [comment]
Hi Tom, 

After testing it,  this version of UMI-tools works very well.  Thank you so much for your help. 

Wenjuan

**Comment by TomSmithCGAT** [comment]
Great. The branch has been merged into master. Thanks for bringing this to our attention and for providing me with the example BAM.

**Pull request merged**
