### PR TITLE
{is} prepare for rsem

### PR DESCRIPTION
**Pull request by IanSudbery**
Add new command that allows UMI-tools output to be used with tools that expect pairs to be adjacent to each other in the output, such as RSEM and salmon.

### CODE REVIEW

**Comment by IanSudbery** [comment]
Fix for #607. This was a branch that was created against 1.1.2, but never integrated into the main trunk.

**Comment by pinin4fjords** [comment]
Will there be a release soon to include this?

**Comment by TomSmithCGAT** [comment]
@pinin4fjords - yes! It looks like the last release (v1.1.4) is now close to a year behind the github repo. 

I'll sort this very soon. I've left Ian to man the ship all by himself for almost all that time so I'll need to aquaint myself with the any updates first.

**Comment by TomSmithCGAT** [comment]
@pinin4fjords - 1.1.5 has now been released on github. I'll check back on bioconda later when the BiocondaBot has had a chance to try and update.

**Comment by pinin4fjords** [comment]
Great- thanks @TomSmithCGAT !

**Comment by pinin4fjords** [comment]
Merged! https://github.com/bioconda/bioconda-recipes/pull/45795 

(I fixed a minor linting issue)

**Comment by TomSmithCGAT** [comment]
Thanks @pinin4fjords. For my own education, what is the `run_export` doing?

**Comment by pinin4fjords** [comment]
See https://bioconda.github.io/contributor/linting.html#missing-run-exports

Obviously feel free to tweak for future builds :-)

**Pull request merged**
