### PR TITLE
Use iterator to reduce memory usage in paired end processessing

### PR DESCRIPTION
**Pull request by IanSudbery**
Fixes issue #25

### CODE REVIEW

**Comment by IanSudbery** [comment]
Just checking this is good with you @TomSmithCGAT

**Comment by TomSmithCGAT** [comment]
Great. Thanks!

**Comment by TomSmithCGAT** [comment]
@IanSudbery I've added in a try, except to make izip python 2 & 3 compatible feda398 . Otherwise we get

``ImportError: cannot import name 'izip'``

**Comment by IanSudbery** [comment]
Ah yes! zip is an iterator by default in py3. Perhaps we should have py3 build tests as well as py2?

**Pull request merged**
